/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmsTxtRouteImport } from './routes/llms.txt'
import { Route as LlmsFullTxtRouteImport } from './routes/llms-full.txt'
import { Route as DocsSplatRouteImport } from './routes/docs/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsTxtRoute = LlmsTxtRouteImport.update({
  id: '/llms/txt',
  path: '/llms/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullTxtRoute = LlmsFullTxtRouteImport.update({
  id: '/llms-full/txt',
  path: '/llms-full/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/$': typeof DocsSplatRoute
  '/llms-full/txt': typeof LlmsFullTxtRoute
  '/llms/txt': typeof LlmsTxtRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/$': typeof DocsSplatRoute
  '/llms-full/txt': typeof LlmsFullTxtRoute
  '/llms/txt': typeof LlmsTxtRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/$': typeof DocsSplatRoute
  '/llms-full/txt': typeof LlmsFullTxtRoute
  '/llms/txt': typeof LlmsTxtRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs/$' | '/llms-full/txt' | '/llms/txt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs/$' | '/llms-full/txt' | '/llms/txt'
  id: '__root__' | '/' | '/docs/$' | '/llms-full/txt' | '/llms/txt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsSplatRoute: typeof DocsSplatRoute
  LlmsFullTxtRoute: typeof LlmsFullTxtRoute
  LlmsTxtRoute: typeof LlmsTxtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms/txt': {
      id: '/llms/txt'
      path: '/llms/txt'
      fullPath: '/llms/txt'
      preLoaderRoute: typeof LlmsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full/txt': {
      id: '/llms-full/txt'
      path: '/llms-full/txt'
      fullPath: '/llms-full/txt'
      preLoaderRoute: typeof LlmsFullTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsSplatRoute: DocsSplatRoute,
  LlmsFullTxtRoute: LlmsFullTxtRoute,
  LlmsTxtRoute: LlmsTxtRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
